const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  email: { type: String, required: true },
  contact: { type: Number, required: true },
  category: { type: String, required: true },
  fatherName: { type: String, required: true },
  motherName: { type: String, required: true },
  fatherOcc: { type: String, required: true },
  motherOcc: { type: String, required: true },
  totalIncome: { type: Number, required: true },
  parentContact: { type: Number, required: true },
  date: { type: Date, default: Date.now },
  isVerified: { type: Boolean, default: false },
  isDeclined: { type: Boolean, default: false },
  religion: { type: String, required: true },
  contact: { type: Number, required: true },
  nationality: { type: String, required: true },
  gender: { type: String, required: true },
  altContact: { type: Number, required: true },
  DOB: { type: Date, required: true },
  country: { type: String, required: true },
  streetAddress: { type: String, required: true },
  locality: { type: String, required: true },
  landmark: { type: String, required: true },
  district: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  zip: { type: String, required: true },
  pio: { type: String, required: true },
  NRI: { type: String, required: true },
  Pcountry: { type: String, required: true },
  PstreetAddress: { type: String, required: true },
  Plocality: { type: String, required: true },
  Plandmark: { type: String, required: true },
  Pdistrict: { type: String, required: true },
  Pcity: { type: String, required: true },
  Pstate: { type: String, required: true },
  pzip: { type: Number, required: true },
  highestQualification: { type: String, required: true },
  tenschoolName: { type: String, required: true },
  tenBoard: { type: String, required: true },
  tweschoolName: { type: String, required: true },
  tweboard: { type: String, required: true },
  twelveMarks: { type: Number, required: true },
  tenMarks: { type: Number, required: true },
  twelveYear: { type: Number, required: true },
  tenYear: { type: Number, required: true },
  JeeMRollNumber: { type: Number, required: true },
  JEEMrank: { type: Number, required: true },
  JeeARollNumber: { type: Number, required: true },
  JEEArank: { type: Number, required: true },
  GATERollNumber: { type: Number, required: true },
  GATErank: { type: Number, required: true },
  UGCNETRollNumber: { type: Number, required: true },
  UGCNETrank: { type: Number, required: true },
  branch: { type: String, required: true },
  domicilestate: { type: String, required: true },
  pwd: { type: String, required: true },
  allotedinstitute: { type: String, required: true },
  allotedCategory: { type: String, required: true },
  remarks: { type: String, required: true },
  roundNumber: { type: Number, required: true },
  CSABstatus: { type: String, required: true },
  csabAllotedInstitute: { type: String, required: true },
  paymentMode: { type: String, required: true },
  transactionId: { type: String, required: true },
  bankName: { type: String, required: true },
  feeAmount: { type: Number, required: true },
  DOD: { type: Date, required: true },
  feeType: { type: String, required: true },
  scholarshipStatus: { type: String, required: true },
  scholarshipName: { type: String, required: true },
  feeYear: { type: Number, required: true },
  feeSemester: { type: String, required: true },
  preferredHostel: { type: String, required: true },
  preferredHostelFloor: { type: Number, required: true },
  roomStyle: { type: String, required: true },
  messFood: { type: String, required: true },
  hostelPaymentMode: { type: String, required: true },
  HostelTid: { type: Number, required: true },
  HBankName: { type: String, required: true },
  HFeeAmount: { type: Number, required: true },
  HDOD: { type: Date, required: true },
});


const Info = mongoose.model("info", userSchema);

module.exports = Info;